import { StyleSheet } from 'react-native';

export default StyleSheet.create(
    { 'lobby-screen':
   { display: 'flex',
     justifyContent: 'center',
     alignItems: 'center',
     flexDirection: 'column',
     marginTop: 24,
     position: 'relative'},
  games: { marginTop: 16 },
  game:
   { width: 270,
     height: 40,
     fontSize: 14,
     color: '#161616',
     backgroundColor: '#FFFFFF',
     shadowOffset: { width: 0, height: 4 },
     shadowRadius: 4,
     shadowColor: 'rgba(0, 0, 0, 0.25)',
     shadowOpacity: 1,
     borderRadius: 2,
     marginBottom: 16,
     display: 'flex',
     justifyContent: 'center',
     alignItems: 'center' },
  'mafia-text-logo': { marginBottom: 24 },
  logo: { marginBottom: 70 },
  'new-game':
   { position: 'absolute',
     left: '5%',
     bottom: '5%',
     display: 'flex',
     alignItems: 'center' },
  'new-game-btn':
   { width: 50,
     height: 50,
     backgroundColor: '#00FFC2',
     shadowOffset: { width: 0, height: 4 },
     shadowRadius: 4,
     shadowColor: 'rgba(0, 0, 0, 0.25)',
     shadowOpacity: 1,
     borderRadius: 50,
     display: 'flex',
     justifyContent: 'center',
     alignItems: 'center',
     fontSize: 36,
     color: '#4B4B4B' },
  'new-game-btn-text': { fontSize: 18, color: '#EFEFEF', marginLeft: 8 },
		 'header': { fontSize: 48, color: '#01FFC2', marginBottom: 12 }}
);
